version: "3.8"
services:
  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit
    ports:
      # необходимо открыть порты, которые используются плагином forward
      - 24224:24224
      - 24224:24224/udp
    volumes:
      # добавляем конфигурацию в контейнер
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/parsers/parsers.conf
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: elasticsearch
    image: docker.arvancloud.ir/elasticsearch:7.16.3
    environment:
      - "discovery.type=single-node"

  kibana:
    container_name: kibana
    image: docker.arvancloud.ir/kibana:7.16.3
    depends_on:
      - "elasticsearch"
    ports:
      - "5601:5601"
